openapi: 3.0.3
info:
  title: "Callback Service"
  description: "Серверное приложение для отслеживания маршрута сообщения"
  version: "1.0"

paths:

  /callback:

    post:
      summary: "Сообщение принято / отправлено"
      description: "Вызвать когда Ваше приложение получает сообщение из другого приложения или пользователь ввёл его. И Вызвать когда Ваше приложение отправляет сообщение в другое приложение или показывает пользователю"
      parameters:
        - name: debug
          in: query
          required: false
          schema:
            description: "Режим отладки. Если true, то ответ придёт с текстом ошибки"
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        200:
          description: "Успешно"
        400:
          description: "Не удалось распарсить Event."
          content:
            text/plain:
              schema:
                description: "Подробный текст ошибки (придёт, если debug == true)"
                type: string

components:

  schemas:

    Action:
      type: string
      enum:
        - SEND
        - RECEIVE

    Application:
      description: "О приложении: автор и язык, на котором написана программа"
      type: object
      required:
        - author
        - language
      properties:
        author:
          type: string
        language:
          type: string

    Event:
      description: "Событие: получено / отправлено; от кого; используемый метод; кому; точное время события; а так же текст ошибки, если таковая произошла"
      type: object
      required:
        - action
        - from
        - over
        - to
        - timestamp
      properties:
        action:
          $ref: "#/components/schemas/Action"
        from:
          $ref: "#/components/schemas/Application"
        over:
          description: "Метод передачи сообщения"
          type: string
        to:
          $ref: "#/components/schemas/Application"
        timestamp:
          description: "Точное время события"
          type: string
          format: date-time
        errorDescription:
          description: "Текст ошибки, если произошла"
          type: string