openapi: 3.0.3
info:
  title: "Logger"
  description: "Серверное приложение для отслеживания маршрута сообщения"
  version: "0.1"
  
paths:

  /receive:
    
    post:
      summary: "Сообщение принято"
      description: "Вызвать когда Ваше приложение получает сообщение из другого приложения или пользователь ввёл его"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid status value
    
  /transmit:
    
    post:
      summary: "Сообщение отправлено"
      description: "Вызвать когда Ваше приложение отправляет сообщение в другое приложение или показывает пользователю"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid status value
  
components:

  schemas:
      
    Application:
      description: "О приложении: автор и язык, на котором написана программа"
      type: object
      required:
        - author
        - language
      properties:
        author:
          type: string
        language:
          type: string
          
    Event:
      description: "Событие: от кого отправлено / пришло сообщение, через какой метод и кому отправлено / пришло, точное время (Unix timestamp) получения / отправки сообщения, а так же текст ошибки, если таковая произошла"
      type: object
      required:
        - from
        - over
        - to
        - timestamp
      properties:
        from:
          $ref: "#/components/schemas/Application"
        over:
          type: string
        to:
          $ref: "#/components/schemas/Application"
        timestamp:
          type: integer
          format: int64
        errorDescription:
          type: string
