openapi: 3.0.3
info:
  title: "Callback Service"
  description: "Серверное приложение для отслеживания маршрута сообщения"
  version: "0.5"
  
paths:

  /callback:
    
    post:
      summary: "Сообщение принято / отправлено"
      description: "Вызвать когда Ваше приложение получает сообщение из другого приложения или пользователь ввёл его. ИЛИ Вызвать когда Ваше приложение отправляет сообщение в другое приложение или показывает пользователю"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        200:
          description: Successful operation
        400:
          description: Invalid status value
  
components:

  schemas:
  
    Action:
      type: string
      enum:
        - SEND
        - RECEIVE
      
    Application:
      description: "О приложении: автор и язык, на котором написана программа"
      type: object
      required:
        - author
        - language
      properties:
        author:
          type: string
        language:
          type: string
          
    Event:
      description: "Событие: получено / отправлено; от кого; используемый метод; кому; точное время события; а так же текст ошибки, если таковая произошла"
      type: object
      required:
        - action
        - from
        - over
        - to
        - timestamp
      properties:
        action:
          $ref: "#/components/schemas/Action"
        from:
          $ref: "#/components/schemas/Application"
        over:
          type: string
        to:
          $ref: "#/components/schemas/Application"
        timestamp:
          type: string
          format: date-time
        errorDescription:
          type: string
